CREATE OR REPLACE VIEW V_ACOMPANHAMENTO_VENDAS_TST AS
WITH
TIPOPLAN AS
(
  SELECT ANOVERSAO, CALDAY, MAX(TIPO) TIPO FROM
  (
         SELECT
              MAX(CAST(SUBSTR(REPLACE(VERSAO,'Est.'),1,4) AS FLOAT)) ANOVERSAO,
              CALDAY,
              TIPO
         FROM V_SOP_GATE
         WHERE
              KEYFIGURE = 'KF00049'
              AND TIPO NOT IN ('00')
         GROUP BY CALDAY, TIPO order by 1, 2, 3
  )
  WHERE
  ANOVERSAO = CASE WHEN EXTRACT(MONTH FROM SYSDATE)>3 THEN EXTRACT(YEAR FROM SYSDATE) ELSE EXTRACT(YEAR FROM SYSDATE)-1 END AND
  CALDAY BETWEEN TRUNC(ADD_MONTHS(SYSDATE,-3), 'MM') AND TRUNC(ADD_MONTHS(SYSDATE,3), 'MM')
  GROUP BY ANOVERSAO, CALDAY
  ORDER BY 2,1,3
),

VENDEDOR AS
(
/*  SELECT V.CUSTOMER,
         V.VENDEDOR,
         V.AGRUP,
         V.CODAGRP,
         C.DESCCLIENTE,
         C.PAISCLIENTE,
         V.PAISVENDA
    FROM (SELECT UPPER("/B28/S_HWDK7NX") CUSTOMER,
                 "/B28/S_HWP7711" VENDEDOR,
                 "/B28/S_HWPBKK1" AGRUP,
                 "/B28/S_HWPO2CZ" CODAGRP,
                 UPPER("/B28/S_HWPIVQW") PAISVENDA
            FROM SAPR3."/B28/PHWDK7NX"@ZWP) V,
         (SELECT B.CUSTOMER, B.TXTMD DESCCLIENTE, A.PAISCLIENTE
            FROM (SELECT A.CUSTOMER, B.TXTSH PAISCLIENTE
                    FROM SAPR3."/BI0/MCUSTOMER"@ZWP A,
                         (SELECT *
                            FROM SAPR3."/BI0/TCOUNTRY"@ZWP
                           WHERE LANGU = 'E') B
                   WHERE A.COUNTRY = B.COUNTRY(+)) A,
                 SAPR3."/BI0/TCUSTOMER"@ZWP B
           WHERE A.CUSTOMER(+) = B.CUSTOMER) C
   WHERE V.CUSTOMER = C.CUSTOMER(+)
*/

  SELECT CASE
           WHEN A.CUSTOMER || '0' = '0' THEN
            B.CUSTOMER
           ELSE
            A.CUSTOMER
         END CUSTOMER,
         A."/BIC/ZEXEC_VEN" VENDEDOR,
         A."/BIC/ZGR_SOP" CODAGRP,
         D.TXTMD AGRUP,
         C.TXTMD DESCCLIENTE,
         E.TXTSH PAISCLIENTE,
         B.PAISVENDA,
         B.INCOTERM
    FROM SAPR3."/BI0/PCUSTOMER"@ZWP A,
         (SELECT CAST(UPPER("/B28/S_HWDK7NX") AS VARCHAR(10)) CUSTOMER,
                 UPPER("/B28/S_HWPIVQW") PAISVENDA, "/B28/S_HWPOWGH" INCOTERM
            FROM SAPR3."/B28/PHWDK7NX"@ZWP) B,
         SAPR3."/BI0/TCUSTOMER"@ZWP C,
         SAPR3."/BI0/TCUSTOMER"@ZWP D,
         (SELECT * FROM SAPR3."/BI0/TCOUNTRY"@ZWP WHERE LANGU = 'E') E
   WHERE A.CUSTOMER = C.CUSTOMER(+)
     AND A.CUSTOMER(+) = B.CUSTOMER
     AND A."/BIC/ZGR_SOP" = D.CUSTOMER(+)
     AND A.COUNTRY = E.COUNTRY(+)
),

SF3 AS
(
    SELECT ROWNUM-25 MX FROM DUAL CONNECT BY ROWNUM < = 75
),

MESES AS
(
    SELECT ROWNUM-1 M3 FROM DUAL CONNECT BY ROWNUM < = 3
)
,


REPLANSF3 AS
(
  SELECT
    ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) MESVERSAO,
    ADD_MONTHS(ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX),MESES.M3) CALDAY,
    TIPOPLAN.ANOVERSAO,
    TIPOPLAN.TIPO
  FROM
    DUAL,
    SF3 CALDAY,
    SF3 MESVERSAO,
    TIPOPLAN,
    MESES
  WHERE
  ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) >= TO_DATE('20160301','YYYYMMDD')
  AND ADD_MONTHS(ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX),MESVERSAO.MX) = TIPOPLAN.CALDAY
  AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) = TIPOPLAN.CALDAY
  AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'),-12)
  --AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) <= TO_DATE(CASE WHEN EXTRACT(MONTH FROM SYSDATE)<4 THEN TO_CHAR(EXTRACT(YEAR FROM SYSDATE)+3) ELSE TO_CHAR(EXTRACT(YEAR FROM SYSDATE)+4) END ||'0301', 'YYYYMMDD')
  --AND ADD_MONTHS(ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX),MESVERSAO.MX) <= TO_DATE(CASE WHEN EXTRACT(MONTH FROM SYSDATE)<4 THEN TO_CHAR(EXTRACT(YEAR FROM SYSDATE)+3) ELSE TO_CHAR(EXTRACT(YEAR FROM SYSDATE)+4) END ||'0301', 'YYYYMMDD')
  AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) <= ADD_MONTHS(ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX),MESVERSAO.MX)
  --AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'),CALDAY.MX) <= TRUNC(SYSDATE, 'MM')
  ORDER BY 1,2,3
),

--ADERENCIA_LT
den11a1 AS (select rownum - 12 mx from dual connect by rownum < = 12),
de0a5 AS (select rownum - 1 mx from dual connect by rownum < = 6),
--de1a5 AS (select rownum  mx from dual connect by rownum < = 5),
--de2a5 AS (select rownum +1 mx from dual connect by rownum < = 4),
mes AS (select rownum - 24 mx from dual connect by rownum < = 25),
contagem as (select rownum - 12 mes from dual connect by rownum < = 14),
de0a2 as (select rownum - 1 mx from dual connect by rownum < = 3),
mesesgate as (select add_months(trunc(sysdate, 'MM'),mes) mesversao, add_months(add_months(trunc(sysdate, 'MM'),mes),mx) calday from dual, contagem, de0a2),
versaogate as (select max(mesversao) versao from V_SOP_GATE where keyfigure='KF00044'),

x AS (
    select 'BRAZIL' ORIGEM, 'BRAZIL' DESTINO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),-2) MESVERSAO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),mx) CALDAY FROM DUAL, de0a5 union all
    select 'BRAZIL' ORIGEM, 'US'     DESTINO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),-2) MESVERSAO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),mx) CALDAY FROM DUAL, de0a5 union all
    select 'BRAZIL' ORIGEM, 'EUROPE' DESTINO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),-2) MESVERSAO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),mx) CALDAY FROM DUAL, de0a5 union all
    select 'PTX'    ORIGEM, 'US'     DESTINO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),-2) MESVERSAO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),mx) CALDAY FROM DUAL, de0a5 union all
    select 'PTX'    ORIGEM, 'EUROPE' DESTINO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),-2) MESVERSAO, ADD_MONTHS(TRUNC(SYSDATE, 'MM'),mx) CALDAY FROM DUAL, de0a5
)
, y AS (
  SELECT origem, destino, add_months(mesversao, mx) MESVERSAO, add_months(CALDAY, mx) CALDAY FROM x, den11a1
),

ADERENCIA_LT AS
(
  SELECT DISTINCT ORIGEM, DESTINO, MESVERSAO, CALDAY FROM Y --WHERE CALDAY BETWEEN ADD_MONTHS(MESVERSAO, 2) AND ADD_MONTHS(MESVERSAO,4)
),

/*(
SELECT  ORIGEM, DESTINO, MESVERSAO, CALDAY, MESREF FROM
(
  SELECT DISTINCT ORIGEM, DESTINO, MESVERSAO, CALDAY, MESREF FROM
  (
    SELECT origem, destino, ADD_MONTHS(MESVERSAO, m.mx) MESVERSAO, ADD_MONTHS(CALDAY, m.mx) CALDAY,  ADD_MONTHS(MESVERSAO, m.mx) MESREF,
        CASE
        WHEN ORIGEM = 'BRAZIL' AND DESTINO = 'BRAZIL' THEN ADD_MONTHS(ADD_MONTHS(MESVERSAO, m.mx),1) ELSE
          CASE
             WHEN ORIGEM = 'BRAZIL' AND DESTINO IN ('EUROPE','US') THEN ADD_MONTHS(ADD_MONTHS(MESVERSAO, m.mx),3) ELSE
             CASE
               WHEN ORIGEM = 'PTX' AND  DESTINO = 'EUROPE' THEN ADD_MONTHS(ADD_MONTHS(MESVERSAO, m.mx),2) ELSE
                  CASE
                     WHEN ORIGEM = 'PTX' AND  DESTINO = 'US' THEN ADD_MONTHS(ADD_MONTHS(MESVERSAO, m.mx),1)
                  END
             END
          END
        END MESREF
     FROM y, mes m
     WHERE  MESVERSAO >=to_date(CASE WHEN TO_CHAR(SYSDATE,'MM')<4 THEN '01/04/'||(TO_CHAR(SYSDATE,'yyyy')-1) else '01/04/'||TO_CHAR(SYSDATE,'yyyy') END, 'dd/mm/yyyy') --AND
     \*ADD_MONTHS(MESVERSAO, m.mx) =
     CASE WHEN ORIGEM = 'BRAZIL' AND DESTINO = 'BRAZIL' THEN TRUNC(ADD_MONTHS(SYSDATE,-1),'MM') ELSE
       CASE WHEN ORIGEM = 'PTX' AND DESTINO = 'US' THEN TRUNC(ADD_MONTHS(SYSDATE,-1),'MM') ELSE
         CASE WHEN ORIGEM = 'PTX' AND DESTINO = 'EUROPE' THEN TRUNC(ADD_MONTHS(SYSDATE,-2),'MM') ELSE TRUNC(ADD_MONTHS(SYSDATE,-3),'MM')
         END
       END*\
     --END
     --AND add_months(CALDAY, mx) BETWEEN  TRUNC(SYSDATE,'MM') AND TRUNC(ADD_MONTHS(SYSDATE,2),'MM')
   ) A
ORDER BY 1, 2, 3, 4
) A WHERE CALDAY BETWEEN MESREF AND ADD_MONTHS(MESREF,2)
),*/

PERIODOGATE AS
(
  SELECT MESVERSAO,
         CASE
           WHEN MESVERSAO < VERSAO AND MESESGATE.CALDAY = MESVERSAO THEN
            MESVERSAO
           ELSE
            CASE
             WHEN MESVERSAO = VERSAO THEN
              MESESGATE.CALDAY
            END
         END CALDAY, '00' TIPO --CASE WHEN TIPO <> '00' THEN TIPO ELSE '00' END TIPO
    FROM MESESGATE, VERSAOGATE--, TIPOPLAN
   WHERE MESVERSAO <= VERSAO AND
   --MESVERSAO = TIPOPLAN.CALDAY (+) AND
         CASE
           WHEN MESVERSAO < VERSAO AND MESESGATE.CALDAY = MESVERSAO THEN
            MESVERSAO
           ELSE
            CASE
             WHEN MESVERSAO = VERSAO THEN
              MESESGATE.CALDAY
            END
         END  IS NOT NULL

),

PERIODOCARTEIRA AS
(
  SELECT MESVERSAO, TRUNC(DTESTOQUE,'MM') CALDAY, DTESTOQUE FROM
  (
    SELECT
      ADD_MONTHS(TO_DATE(A.DTESTOQUE,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.DTESTOQUE,'YYYYMMDD'))+1,mx-2) MESVERSAO,
      MAX(TO_DATE(A.DTESTOQUE,'YYYYMMDD')) DTESTOQUE
    FROM SAPR3.ZCARTEIRADIARIO@ZLP A, de0a2 B WHERE TO_DATE(A.DTESTOQUE,'YYYYMMDD')= (select trunc(sysdate,'DD') from dual)
    GROUP BY ADD_MONTHS(TO_DATE(A.DTESTOQUE,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.DTESTOQUE,'YYYYMMDD'))+1,mx-2)
  ) A
)
--select * from PERIODOCARTEIRA
,

PERIODOVENDAS AS
(
  SELECT MESVERSAO,
         CASE
           WHEN MESVERSAO < VERSAO THEN
            MESVERSAO
           ELSE
            CASE
             WHEN MESVERSAO = VERSAO THEN
              CALDAY
            END
         END CALDAY
    FROM MESESGATE, VERSAOGATE
   WHERE MESVERSAO <= VERSAO
),

GATE_FLAG AS
(
   SELECT CASE WHEN MAX(MESVERSAO) <> TRUNC(SYSDATE,'MM') THEN 0 ELSE 1 END MESVERSAO FROM V_SOP_GATE WHERE KEYFIGURE IN ('KF00044')
),

VENDAS AS
(
SELECT A.MATERIAL, B.MESVERSAO, B.CALDAY, A.GRUPOANALISE, A.SITE, A.SUBSITE, A.AGRUPAMENTO, A.FAMILIA, A.SEGMENTO, A.CUSTOMER,
       A.VENDEDOR, A.AGRUP, A.CODAGRP, A.DESCCLIENTE, A.PAISCLIENTE, A.PAISVENDA, A.INCOTERM, A.PAIS_FAT, A.EXPSITE, A.CONSULTA, A.QTD_VENDAS,
       A.VAL_VENDAS, A.QTD_CARTEIRA, A.VAL_CARTEIRA, A.QTD_BUDGET, A.VAL_BUDGET, A.QTD_BUDGET_ORIG, A.VAL_BUDGET_ORIG, A.QTD_SOP, A.VAL_SOP, A.GATE, A.VAL_GATE, A.GATE_ORIG, A.VAL_GATE_ORIG,
       A.LEADTIME, A.REPLAN FROM
  (
    SELECT
        A.MATERIAL,
        TO_DATE(A.CALDAY, 'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.CALDAY, 'YYYYMMDD'))+1 MESVERSAO,
        TO_DATE(A.CALDAY, 'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.CALDAY, 'YYYYMMDD'))+1 CALDAY,
        B.GRUPOANALISETXT GRUPOANALISE,
        CASE WHEN B.SITE <>'PTX' AND B.SITE <> 'NAO ATRIBUIDO'  THEN 'BRAZIL' ELSE B.SITE END SITE,
        B.SUBSITETXT SUBSITE,
        B.AGRUPTXT AGRUPAMENTO,
        B.FAMILIATXT FAMILIA,
        B.SEGTXT SEGMENTO,
        A.SHIP_TO CUSTOMER,
        C.VENDEDOR,
        C.AGRUP,
        C.CODAGRP,
        C.DESCCLIENTE,
        C.PAISCLIENTE,
        C.PAISVENDA,
        C.INCOTERM,
        CASE WHEN A.PLANT IN ('LVAQ','LA02','DFAQ','BISJ','BIBG','BFBG','LVBG','LVSJ') THEN 'BRAZIL'
             WHEN A.PLANT = 'PTX' THEN 'US'
             WHEN A.PLANT IN ('ANRU','ANRC','GERM') THEN 'EUROPE'
        ELSE A.PLANT END PAIS_FAT,
        CASE WHEN A.DOC_TYPE IN ('YCS', 'YUS1') THEN 'BRAZIL'
             WHEN A.PLANT IN('LVAQ','LA02','DFAQ','BISJ','BIBG','BFBG','LVBG','LVSJ') THEN 'BRAZIL'
             WHEN A.PLANT = 'PTX' THEN 'US'
             WHEN A.PLANT IN ('ANRU','ANRC','GERM') THEN 'EUROPE'
        ELSE A.PLANT END EXPSITE,
        'VENDAS' CONSULTA,
        SUM(NVL(CASE A.BASE_UOM WHEN 'LB' THEN A.QUANTITY/2204.6 ELSE A.QUANTITY/1000 END,0)) QTD_VENDAS,
        SUM(NVL(A."/BIC/VL_EXWRKS"+A."/BIC/VL_FRETE"+A."/BIC/VL_OUTDSP"+A."/BIC/VL_SEGURO"+A."/BIC/VL_FRETBR"+A."/BIC/VL_DESPBR",0)) VAL_VENDAS,
        0 QTD_CARTEIRA,
        0 VAL_CARTEIRA,
        0 QTD_BUDGET,
        0 VAL_BUDGET,
        0 QTD_BUDGET_ORIG,
        0 VAL_BUDGET_ORIG,
        0 QTD_SOP,
        0 VAL_SOP,
        0 GATE,
        0 VAL_GATE,
        0 GATE_ORIG,
        0 VAL_GATE_ORIG,
        0 LEADTIME,
        0 REPLAN
      --A."/BIC/VL_EXWRKS" VALOR
    FROM
      SAPR3."/BIC/AZSD_O0300"@ZWP  A,
      V_PRODUTO_PL B,
      VENDEDOR C
    WHERE
      A.SHIP_TO  NOT IN  ( ' ','0000350411','0000351406', '0000036941', 'EXTRA_SF_E', 'EXTRA_SF_U') AND
      --'FEED_05', 'FEED_07', 'FEED_08', 'FEED_09', 'FEED_46', 'FOOD_01', 'FOOD_03', 'FOOD_05', 'FOOD_06',
      --'FOOD_07', 'FOOD_08', 'FOOD_09', 'FOOD_10', 'FOOD_13', 'FOOD_14', 'FOOD_16', 'FOOD_17', 'FOOD_18',
      --'FOOD_22', 'FOOD_23', 'FOOD_24', 'FOOD_25', 'FOOD_26', 'FOOD_27', 'FOOD_28', 'FOOD_29', 'FOOD_30',
      --'FOOD_31', 'FOOD_32', 'FOOD_33', 'FOOD_34', 'FOOD_35', 'FOOD_36', 'FOOD_37', 'FOOD_38', 'FOOD_39',
      --'FOOD_40', 'FOOD_41', 'FOOD_42', 'FOOD_43', 'FOOD_44', 'FOOD_45' ) AND
      A.DOC_TYPE NOT IN ('YKE') AND
      C.VENDEDOR  NOT IN  ( ' ','ZILOR','OLD', 'Extra_SF' ) AND
      B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA') AND
      B.SITE <> 'NAO ATRIBUIDO' AND
      A.PLANT  NOT IN  ( 'LVBI','LA01' ) AND
      A.MATERIAL = B.PRODUTO AND
      A.SHIP_TO = C.CUSTOMER
    GROUP BY
      A.MATERIAL,
      TO_DATE(A.CALDAY, 'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.CALDAY, 'YYYYMMDD'))+1,
      B.GRUPOANALISETXT,
      CASE WHEN B.SITE <>'PTX' AND B.SITE<>'NAO ATRIBUIDO'  THEN 'BRAZIL' ELSE B.SITE END,
      B.SUBSITETXT,
      B.AGRUPTXT,
      B.FAMILIATXT,
      B.SEGTXT,
      A.SHIP_TO,
      C.VENDEDOR,
      C.AGRUP,
      C.CODAGRP,
      C.DESCCLIENTE,
      C.PAISCLIENTE,
      C.PAISVENDA,
      C.INCOTERM,
      CASE WHEN A.PLANT IN ('LVAQ','LA02','DFAQ','BISJ','BIBG','BFBG','LVBG','LVSJ') THEN 'BRAZIL'
           WHEN A.PLANT = 'PTX' THEN 'US'
           WHEN A.PLANT IN ('ANRU','ANRC','GERM') THEN 'EUROPE'
      ELSE A.PLANT END,
      CASE WHEN A.DOC_TYPE IN ('YCS', 'YUS1') THEN 'BRAZIL'
           WHEN A.PLANT IN('LVAQ','LA02','DFAQ','BISJ','BIBG','BFBG','LVBG','LVSJ') THEN 'BRAZIL'
           WHEN A.PLANT = 'PTX' THEN 'US'
           WHEN A.PLANT IN ('ANRU','ANRC','GERM') THEN 'EUROPE'
      ELSE A.PLANT END
  ) A, MESESGATE B
WHERE
A.CALDAY = B.CALDAY
),

CARTEIRA AS
(
  SELECT
    A.MATNR MATERIAL,
    D.MESVERSAO,
    --TO_DATE(A.VDATU,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.VDATU,'YYYYMMDD'))+1 CALDAY,
    CASE WHEN A.FKDAT NOT IN (' ','00000000') THEN TO_DATE(A.FKDAT,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.FKDAT,'YYYYMMDD'))+1
      ELSE TO_DATE(A.VDATU,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.VDATU,'YYYYMMDD'))+1 END CALDAY,
    B.GRUPOANALISETXT GRUPOANALISE,
    CASE WHEN B.SITE <>'PTX' AND B.SITE <> 'NAO ATRIBUIDO'  THEN 'BRAZIL' ELSE B.SITE END SITE,
    B.SUBSITETXT SUBSITE,
    B.AGRUPTXT AGRUPAMENTO,
    B.FAMILIATXT FAMILIA,
    B.SEGTXT SEGMENTO,
    A.KUNNR CUSTOMER,
    C.VENDEDOR,
    C.AGRUP,
    C.CODAGRP,
    C.DESCCLIENTE,
    C.PAISCLIENTE,
    C.PAISVENDA,
    C.INCOTERM,
    CASE WHEN A.WERKS IN ('LVAQ','LA02','DFAQ','BISJ','BIBG','BFBG','LVBG','LVSJ') THEN 'BRAZIL'
         WHEN A.WERKS = 'PTX' THEN 'US'
         WHEN A.WERKS IN ('ANRU','ANRC','GERM') THEN 'EUROPE'
    ELSE  A.WERKS END PAIS_FAT,
    CASE A.WERKS
      WHEN 'LA02' THEN 'BRAZIL'
      WHEN 'LVAQ' THEN 'BRAZIL'
      WHEN 'BISJ' THEN 'BRAZIL'
      WHEN 'BIBG' THEN 'BRAZIL'
      WHEN 'DFAQ' THEN 'BRAZIL'
      WHEN 'BFBG' THEN 'BRAZIL'
      WHEN 'LVBG' THEN 'BRAZIL'
      WHEN 'LVSJ' THEN 'BRAZIL'
      WHEN 'ANRU' THEN 'EUROPE'
      WHEN 'ANRC' THEN 'EUROPE'
      WHEN 'GERM' THEN 'EUROPE'
      WHEN 'PTX'  THEN 'US'
    END AS EXPSITE,
    'CARTEIRA' CONSULTA,
    0 QTD_VENDAS,
    0 VAL_VENDAS,
    SUM(NVL(CASE WHEN A.VRKME='LB' THEN  A.KWMENG/2204.62 ELSE A.KWMENG/1000 END,0))QTD_CARTEIRA,
    SUM(NVL(A.NETWR,0)) VAL_CARTEIRA,
    0 QTD_BUDGET,
    0 VAL_BUDGET,
    0 BUDGET_ORIG,
    0 VAL_BUDGET_ORIG,
    0 QTD_SOP,
    0 VAL_SOP,
    0 GATE,
    0 VAL_GATE,
    0 GATE_ORIG,
    0 VAL_GATE_ORIG,
    0 LEADTIME,
    0 REPLAN
  FROM
  SAPR3.ZCARTEIRADIARIO@ZLP A,
  V_PRODUTO_PL B,
  VENDEDOR C,
  PERIODOCARTEIRA D
  WHERE
  TO_DATE(A.DTESTOQUE,'YYYYMMDD')= D.DTESTOQUE
  AND A.MATNR = B.PRODUTO
  AND A.KUNNR = C.CUSTOMER
  --AND A.KUNNR = D.CUSTOMER
  AND A.KUNNR  NOT IN  ( ' ','0000350411','0000351406', '0000036941', 'EXTRA_SF_E', 'EXTRA_SF_U') AND
      --'FEED_05', 'FEED_07', 'FEED_08', 'FEED_09', 'FEED_46', 'FOOD_01', 'FOOD_03', 'FOOD_05', 'FOOD_06',
      --'FOOD_07', 'FOOD_08', 'FOOD_09', 'FOOD_10', 'FOOD_13', 'FOOD_14', 'FOOD_16', 'FOOD_17', 'FOOD_18',
      --'FOOD_22', 'FOOD_23', 'FOOD_24', 'FOOD_25', 'FOOD_26', 'FOOD_27', 'FOOD_28', 'FOOD_29', 'FOOD_30',
      --'FOOD_31', 'FOOD_32', 'FOOD_33', 'FOOD_34', 'FOOD_35', 'FOOD_36', 'FOOD_37', 'FOOD_38', 'FOOD_39',
      --'FOOD_40', 'FOOD_41', 'FOOD_42', 'FOOD_43', 'FOOD_44', 'FOOD_45' ) AND
  C.VENDEDOR  NOT IN  ( ' ','ZILOR','OLD', 'Extra_SF' )
  AND B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA')
  AND A.AUART <> 'YKBB'
  --and A.DTESTOQUE = '20160224'
  --and a.kunnr = '0000351962'
  GROUP BY
  A.MATNR,
    D.MESVERSAO,
    --TO_DATE(A.VDATU,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.VDATU,'YYYYMMDD'))+1,
    CASE WHEN A.FKDAT NOT IN (' ','00000000') THEN TO_DATE(A.FKDAT,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.FKDAT,'YYYYMMDD'))+1
      ELSE TO_DATE(A.VDATU,'YYYYMMDD')-EXTRACT(DAY FROM TO_DATE(A.VDATU,'YYYYMMDD'))+1 END,
    B.GRUPOANALISETXT,
    CASE WHEN B.SITE <>'PTX' AND B.SITE <> 'NAO ATRIBUIDO'  THEN 'BRAZIL' ELSE B.SITE END,
    B.SUBSITETXT,
    B.AGRUPTXT,
    B.FAMILIATXT,
    B.SEGTXT,
    A.KUNNR,
    C.VENDEDOR,
    C.AGRUP,
    C.CODAGRP,
    C.DESCCLIENTE,
    C.PAISCLIENTE,
    C.PAISVENDA,
    C.INCOTERM,
  CASE WHEN A.WERKS IN ('LVAQ','LA02','DFAQ','BISJ','BIBG','BFBG','LVBG','LVSJ') THEN 'BRAZIL'
       WHEN A.WERKS = 'PTX' THEN 'US'
       WHEN A.WERKS IN ('ANRU','ANRC','GERM') THEN 'EUROPE'
  ELSE A.WERKS END,
    CASE A.WERKS
      WHEN 'LA02' THEN 'BRAZIL'
      WHEN 'LVAQ' THEN 'BRAZIL'
      WHEN 'BISJ' THEN 'BRAZIL'
      WHEN 'BIBG' THEN 'BRAZIL'
      WHEN 'DFAQ' THEN 'BRAZIL'
      WHEN 'BFBG' THEN 'BRAZIL'
      WHEN 'LVBG' THEN 'BRAZIL'
      WHEN 'LVSJ' THEN 'BRAZIL'
      WHEN 'ANRU' THEN 'EUROPE'
      WHEN 'ANRC' THEN 'EUROPE'
      WHEN 'GERM' THEN 'EUROPE'
      WHEN 'PTX'  THEN 'US'
    END
),

--PLANO (BUDGET)
BUDGET AS
(
  SELECT
     A.MATERIAL,
     D.MESVERSAO,
     --A.MESVERSAO,
     D.CALDAY,
     B.GRUPOANALISETXT GRUPOANALISE,
     A.SITE,
     B.SUBSITETXT SUBSITE,
     B.AGRUPTXT AGRUPAMENTO,
     B.FAMILIATXT FAMILIA,
     B.SEGTXT SEGMENTO,
     A.CUSTOMER,
     C.VENDEDOR,
     C.AGRUP,
     C.CODAGRP,
     C.DESCCLIENTE,
     C.PAISCLIENTE,
     C.PAISVENDA,
     C.INCOTERM,
     A.PAIS_FAT,
     A.EXPSITE,
     'BUDGET' CONSULTA,
     0 QTD_VENDAS,
     0 VAL_VENDAS,
     0 QTD_CARTEIRA,
     0 VAL_CATEIRA,
     SUM(NVL(A.QUANTITY,0)) BUDGET,
     SUM(NVL(A.AMOUNT,0))+SUM(NVL(A.FRETE,0)) VAL_BUDGET,
     0 BUDGET_ORIG,
     0 VAL_BUDGET_ORIG,
     0 QTD_SOP,
     0 VAL_SOP,
     0 GATE,
     0 VAL_GATE,
     0 GATE_ORIG,
     0 VAL_GATE_ORIG,
     0 LEADTIME,
     0 REPLAN
  FROM
     V_SOP_GATE A,
     V_PRODUTO_PL B,
     VENDEDOR C,
     REPLANSF3 D
  WHERE
     --A.CALDAY BETWEEN TRUNC(SYSDATE, 'MM') AND TRUNC(ADD_MONTHS(SYSDATE,2), 'MM') AND
     A.KEYFIGURE IN ('KF00049') AND
     A.CURRENCY NOT IN ('BRL', 'EUR') AND
     A.MATERIAL <> ' ' AND A.MATERIAL IS NOT NULL AND
     --A.TIPO   IN  ('01') AND
     UPPER(A.EXPSITE)  <>  'GLOBAL' AND
     A.CUSTOMER  NOT IN  ( ' ','0000350411','0000351406', '0000036941', 'EXTRA_SF_E', 'EXTRA_SF_U') AND
      --'FEED_05', 'FEED_07', 'FEED_08', 'FEED_09', 'FEED_46', 'FOOD_01', 'FOOD_03', 'FOOD_05', 'FOOD_06',
      --'FOOD_07', 'FOOD_08', 'FOOD_09', 'FOOD_10', 'FOOD_13', 'FOOD_14', 'FOOD_16', 'FOOD_17', 'FOOD_18',
      --'FOOD_22', 'FOOD_23', 'FOOD_24', 'FOOD_25', 'FOOD_26', 'FOOD_27', 'FOOD_28', 'FOOD_29', 'FOOD_30',
      --'FOOD_31', 'FOOD_32', 'FOOD_33', 'FOOD_34', 'FOOD_35', 'FOOD_36', 'FOOD_37', 'FOOD_38', 'FOOD_39',
      --'FOOD_40', 'FOOD_41', 'FOOD_42', 'FOOD_43', 'FOOD_44', 'FOOD_45' ) AND
     A.VENDEDOR  NOT IN  ( ' ','ZILOR','OLD', 'Extra_SF' ) AND
     B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA') AND
     A.SITE  NOT IN  ( 'NAO ATRIBUIDO'  ) AND
     A.MATERIAL = B.PRODUTO AND
     A.CUSTOMER = C.CUSTOMER AND
     A.CALDAY = D.CALDAY AND
     A.TIPO = D.TIPO AND
     A.ANOVERSAO = D.ANOVERSAO
     --and A.CALDAY='01-02-2016' and B.SEGTXT ='FOOD'
     --AND A.customer = '0000351962'
  GROUP BY
     A.MATERIAL,
     D.MESVERSAO,
     D.CALDAY,
     B.GRUPOANALISETXT,
     A.SITE,
     B.SUBSITETXT,
     B.AGRUPTXT,
     B.FAMILIATXT,
     B.SEGTXT,
     A.CUSTOMER,
     C.VENDEDOR,
     C.AGRUP,
     C.CODAGRP,
     C.DESCCLIENTE,
     C.PAISCLIENTE,
     A.PAIS_FAT,
     C.PAISVENDA,
     C.INCOTERM,
     A.EXPSITE,
     A.CURRENCY,
     A.KEYFIGURE
),

--PLANO ORIGINAL (BUDGET)
BUDGET_ORIGINAL AS
(
  SELECT
     A.MATERIAL,
     D.MESVERSAO1,
     --A.MESVERSAO,
     D.CALDAY,
     B.GRUPOANALISETXT GRUPOANALISE,
     A.SITE,
     B.SUBSITETXT SUBSITE,
     B.AGRUPTXT AGRUPAMENTO,
     B.FAMILIATXT FAMILIA,
     B.SEGTXT SEGMENTO,
     A.CUSTOMER,
     C.VENDEDOR,
     C.AGRUP,
     C.CODAGRP,
     C.DESCCLIENTE,
     C.PAISCLIENTE,
     C.PAISVENDA,
     C.INCOTERM,
     A.PAIS_FAT,
     A.EXPSITE,
     'BUDGET' CONSULTA,
     0 QTD_VENDAS,
     0 VAL_VENDAS,
     0 QTD_CARTEIRA,
     0 VAL_CATEIRA,
     0 BUDGET,
     0 VAL_BUDGET,
     SUM(NVL(A.QUANTITY,0)) BUDGET_ORIG,
     SUM(NVL(A.AMOUNT,0))+SUM(NVL(A.FRETE,0)) VAL_BUDGET_ORIG,
     0 QTD_SOP,
     0 VAL_SOP,
     0 GATE,
     0 VAL_GATE,
     0 GATE_ORIG,
     0 VAL_GATE_ORIG,
     0 LEADTIME,
     0 REPLAN
  FROM
     V_SOP_GATE A,
     V_PRODUTO_PL B,
     VENDEDOR C,
     (SELECT DISTINCT MESVERSAO, ADD_MONTHS(MESVERSAO,-mx) MESVERSAO1, CALDAY, CALMONTH, TIPO  FROM V_SOP_GATE A, den11a1 B WHERE A.KEYFIGURE IN ('KF00049') AND TIPO = '01'
             AND EXTRACT(YEAR FROM MESVERSAO)= (SELECT CASE
                                                       WHEN EXTRACT(MONTH FROM SYSDATE) <= 3 THEN
                                                        EXTRACT(YEAR FROM SYSDATE) - 1
                                                       ELSE
                                                        EXTRACT(YEAR FROM SYSDATE)
                                                     END
                                                FROM DUAL)) D
  WHERE
     --A.CALDAY BETWEEN TRUNC(SYSDATE, 'MM') AND TRUNC(ADD_MONTHS(SYSDATE,2), 'MM') AND
     A.KEYFIGURE IN ('KF00049') AND
     A.CURRENCY NOT IN ('BRL', 'EUR') AND
     A.MATERIAL <> ' ' AND A.MATERIAL IS NOT NULL AND
     --A.TIPO   IN  ('01') AND
     UPPER(A.EXPSITE)  <>  'GLOBAL' AND
     A.CUSTOMER  NOT IN  ( ' ','0000350411','0000351406', '0000036941', 'EXTRA_SF_E', 'EXTRA_SF_U') AND
      --'FEED_05', 'FEED_07', 'FEED_08', 'FEED_09', 'FEED_46', 'FOOD_01', 'FOOD_03', 'FOOD_05', 'FOOD_06',
      --'FOOD_07', 'FOOD_08', 'FOOD_09', 'FOOD_10', 'FOOD_13', 'FOOD_14', 'FOOD_16', 'FOOD_17', 'FOOD_18',
      --'FOOD_22', 'FOOD_23', 'FOOD_24', 'FOOD_25', 'FOOD_26', 'FOOD_27', 'FOOD_28', 'FOOD_29', 'FOOD_30',
      --'FOOD_31', 'FOOD_32', 'FOOD_33', 'FOOD_34', 'FOOD_35', 'FOOD_36', 'FOOD_37', 'FOOD_38', 'FOOD_39',
      --'FOOD_40', 'FOOD_41', 'FOOD_42', 'FOOD_43', 'FOOD_44', 'FOOD_45' ) AND
     A.VENDEDOR  NOT IN  ( ' ','ZILOR','OLD', 'Extra_SF' ) AND
     B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA') AND
     A.SITE  NOT IN  ( 'NAO ATRIBUIDO'  ) AND
     A.MATERIAL = B.PRODUTO AND
     A.CUSTOMER = C.CUSTOMER AND
     A.CALDAY = D.CALDAY AND
     A.TIPO = D.TIPO AND
     A.MESVERSAO = D.MESVERSAO
     --and A.CALDAY='01-02-2016' and B.SEGTXT ='FOOD'
     --AND A.customer = '0000351962'
  GROUP BY
     A.MATERIAL,
     D.MESVERSAO1,
     D.CALDAY,
     B.GRUPOANALISETXT,
     A.SITE,
     B.SUBSITETXT,
     B.AGRUPTXT,
     B.FAMILIATXT,
     B.SEGTXT,
     A.CUSTOMER,
     C.VENDEDOR,
     C.AGRUP,
     C.CODAGRP,
     C.DESCCLIENTE,
     C.PAISCLIENTE,
     A.PAIS_FAT,
     C.PAISVENDA,
     C.INCOTERM,
     A.EXPSITE,
     A.CURRENCY,
     A.KEYFIGURE
),


--PLANO SOP
SOP AS
(
  SELECT
     A.MATERIAL,
     ADD_MONTHS(D.MESVERSAO,2) MESVERSAO,
     --D.MESREF,
     D.CALDAY,
     B.GRUPOANALISETXT GRUPOANALISE,
     A.SITE,
     B.SUBSITETXT SUBSITE,
     B.AGRUPTXT AGRUPAMENTO,
     B.FAMILIATXT FAMILIA,
     B.SEGTXT SEGMENTO,
     A.CUSTOMER,
     C.VENDEDOR,
     C.AGRUP,
     C.CODAGRP,
     C.DESCCLIENTE,
     C.PAISCLIENTE,
     C.PAISVENDA,
     C.INCOTERM,
     A.PAIS_FAT,
     A.EXPSITE,
     'SOP' CONSULTA,
     0 QTD_VENDAS,
     0 VAL_VENDAS,
     0 QTD_CARTEIRA,
     0 VAL_CARTEIRA,
     0 QTD_BUDGET,
     0 VAL_BUDGET,
     0 BUDGET_ORIG,
     0 VAL_BUDGET_ORIG,
     SUM(NVL(A.QUANTITY,0)) QTD_SOP,
     SUM(NVL(A.AMOUNT,0))+SUM(NVL(A.FRETE,0)) VAL_SOP ,
     0 GATE,
     0 VAL_GATE,
     0 GATE_ORIG,
     0 VAL_GATE_ORIG,
     0 LEADTIME,
     0 REPLAN
  FROM
     V_SOP_GATE A,
     V_PRODUTO_PL B,
     VENDEDOR C,
     ADERENCIA_LT D
  WHERE
     --D.MESVERSAO >= TRUNC(ADD_MONTHS(SYSDATE,-3), 'MM') AND
     --A.CALDAY BETWEEN TRUNC(SYSDATE, 'MM') AND TRUNC(ADD_MONTHS(SYSDATE,2), 'MM') AND
     A.KEYFIGURE IN ('KF00049') AND
     A.MESVERSAO IS NOT NULL AND
     --B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA') AND
     A.CURRENCY NOT IN ('BRL', 'EUR') AND
     A.MATERIAL <> ' ' AND A.MATERIAL IS NOT NULL AND
     A.TIPO  IN  ('00') AND
     UPPER(A.EXPSITE)  <>  'GLOBAL' AND
     A.CUSTOMER  NOT IN  ( ' ','0000350411','0000351406', '0000036941', 'EXTRA_SF_E', 'EXTRA_SF_U') AND
      --'FEED_05', 'FEED_07', 'FEED_08', 'FEED_09', 'FEED_46', 'FOOD_01', 'FOOD_03', 'FOOD_05', 'FOOD_06',
      --'FOOD_07', 'FOOD_08', 'FOOD_09', 'FOOD_10', 'FOOD_13', 'FOOD_14', 'FOOD_16', 'FOOD_17', 'FOOD_18',
      --'FOOD_22', 'FOOD_23', 'FOOD_24', 'FOOD_25', 'FOOD_26', 'FOOD_27', 'FOOD_28', 'FOOD_29', 'FOOD_30',
      --'FOOD_31', 'FOOD_32', 'FOOD_33', 'FOOD_34', 'FOOD_35', 'FOOD_36', 'FOOD_37', 'FOOD_38', 'FOOD_39',
      --'FOOD_40', 'FOOD_41', 'FOOD_42', 'FOOD_43', 'FOOD_44', 'FOOD_45' ) AND
     A.VENDEDOR  NOT IN  ( ' ','ZILOR','OLD', 'Extra_SF' ) AND
     B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA') AND
     A.SITE  NOT IN  ( 'NAO ATRIBUIDO'  ) AND
     A.MATERIAL = B.PRODUTO AND
     A.CUSTOMER = C.CUSTOMER AND
     A.MESVERSAO = D.MESVERSAO AND
     A.CALDAY = D.CALDAY AND
     A.SITE = D.ORIGEM AND
     A.PAIS_FAT = D.DESTINO
  GROUP BY
     A.MATERIAL,
     D.MESVERSAO,
     D.CALDAY,
     B.GRUPOANALISETXT,
     A.SITE,
     B.SUBSITETXT,
     B.AGRUPTXT,
     B.FAMILIATXT,
     B.SEGTXT,
     A.CUSTOMER,
     C.VENDEDOR,
     C.AGRUP,
     C.CODAGRP,
     C.DESCCLIENTE,
     C.PAISCLIENTE,
     A.PAIS_FAT,
     C.PAISVENDA,
     C.INCOTERM,
     A.EXPSITE,
     A.CURRENCY,
     A.KEYFIGURE
),


--PLANO GATE
GATE AS
(
SELECT A.MATERIAL, CASE WHEN (SELECT * FROM GATE_FLAG) <> 0 THEN B.MESVERSAO ELSE ADD_MONTHS(B.MESVERSAO,1) END MESVERSAO,
       B.CALDAY, A.GRUPOANALISE, A.SITE, A.SUBSITE, A.AGRUPAMENTO, A.FAMILIA, A.SEGMENTO, A.CUSTOMER,
       A.VENDEDOR, A.AGRUP, A.CODAGRP, A.DESCCLIENTE, A.PAISCLIENTE, A.PAISVENDA, A.INCOTERM, A.PAIS_FAT, A.EXPSITE, A.CONSULTA, A.QTD_VENDAS,
       A.VAL_VENDAS, A.QTD_CARTEIRA, A.VAL_CARTEIRA, A.QTD_BUDGET, A.VAL_BUDGET, A.QTD_BUDGET_ORIG, A.VAL_BUDGET_ORIG, A.QTD_SOP, A.VAL_SOP, A.GATE, A.VAL_GATE, A.GATE_ORIG, A.VAL_GATE_ORIG,
       A.LEADTIME, A.REPLAN FROM
  (
    SELECT
       A.MATERIAL,
       A.MESVERSAO,
       --A.MESVERSAO,
       A.CALDAY,
       B.GRUPOANALISETXT GRUPOANALISE,
       A.SITE,
       B.SUBSITETXT SUBSITE,
       B.AGRUPTXT AGRUPAMENTO,
       B.FAMILIATXT FAMILIA,
       B.SEGTXT SEGMENTO,
       A.CUSTOMER,
       C.VENDEDOR,
       C.AGRUP,
       C.CODAGRP,
       C.DESCCLIENTE,
       C.PAISCLIENTE,
       C.PAISVENDA,
       C.INCOTERM,
       A.PAIS_FAT,
       A.EXPSITE,
       'GATE' CONSULTA,
       0 QTD_VENDAS,
       0 VAL_VENDAS,
       0 QTD_CARTEIRA,
       0 VAL_CARTEIRA,
       0 QTD_BUDGET,
       0 VAL_BUDGET,
       0 QTD_BUDGET_ORIG,
       0 VAL_BUDGET_ORIG,
       0 QTD_SOP,
       0 VAL_SOP,
       SUM(NVL(CASE WHEN A.KEYFIGURE IN ('KF00044') THEN A.QUANTITY ELSE 0 END,0)) GATE,
       SUM(NVL(CASE WHEN A.KEYFIGURE IN ('KF00044') THEN A.AMOUNT ELSE 0 END,0))+SUM(NVL(CASE WHEN A.KEYFIGURE IN ('KF00044') THEN A.FRETE ELSE 0 END,0)) VAL_GATE,
       SUM(NVL(CASE WHEN A.KEYFIGURE IN ('KF00044_0') THEN A.QUANTITY ELSE 0 END,0)) GATE_ORIG,
       SUM(NVL(CASE WHEN A.KEYFIGURE IN ('KF00044_0') THEN A.AMOUNT ELSE 0 END,0))+SUM(NVL(CASE WHEN A.KEYFIGURE IN ('KF00044_0') THEN A.FRETE ELSE 0 END,0)) VAL_GATE_ORIG,
       SUM(NVL(D.QUANTITY,0)) LEADTIME,
       0 REPLAN
    FROM
       V_SOP_GATE A,
       V_PRODUTO_PL B,
       VENDEDOR C,
       (SELECT DISTINCT EXPSITE, INCOTERMS, BLOCO, QUANTITY from V_SOP_GATE where KEYFIGURE = 'KF00013') D,
       PERIODOGATE E
       --GATESF E
    WHERE
       --A.CALDAY BETWEEN TRUNC(SYSDATE, 'MM') AND TRUNC(ADD_MONTHS(SYSDATE,2), 'MM') AND
       --A.MESVERSAO = TRUNC(SYSDATE, 'MM') AND
       A.KEYFIGURE IN ('KF00044','KF00044_0') AND
       A.CURRENCY NOT IN ('BRL', 'EUR') AND
       A.MATERIAL <> ' ' AND A.MATERIAL IS NOT NULL AND
       --A.TIPO  IN  ('00') AND
       A.TIPO = E.TIPO AND
       UPPER(A.EXPSITE)  <>  'GLOBAL' AND
       A.CUSTOMER  NOT IN  ( ' ','0000350411','0000351406', '0000036941', 'EXTRA_SF_E', 'EXTRA_SF_U') AND
      --'FEED_05', 'FEED_07', 'FEED_08', 'FEED_09', 'FEED_46', 'FOOD_01', 'FOOD_03', 'FOOD_05', 'FOOD_06',
      --'FOOD_07', 'FOOD_08', 'FOOD_09', 'FOOD_10', 'FOOD_13', 'FOOD_14', 'FOOD_16', 'FOOD_17', 'FOOD_18',
      --'FOOD_22', 'FOOD_23', 'FOOD_24', 'FOOD_25', 'FOOD_26', 'FOOD_27', 'FOOD_28', 'FOOD_29', 'FOOD_30',
      --'FOOD_31', 'FOOD_32', 'FOOD_33', 'FOOD_34', 'FOOD_35', 'FOOD_36', 'FOOD_37', 'FOOD_38', 'FOOD_39',
      --'FOOD_40', 'FOOD_41', 'FOOD_42', 'FOOD_43', 'FOOD_44', 'FOOD_45' ) AND
       A.VENDEDOR  NOT IN  ( ' ','ZILOR','OLD', 'Extra_SF' ) AND
       B.GRUPOANALISETXT NOT IN ('LEV- LEVEDURA') AND
       A.SITE  NOT IN  ( 'NAO ATRIBUIDO'  ) AND
       A.MATERIAL = B.PRODUTO AND
       A.CUSTOMER = C.CUSTOMER AND
       A.EXPSITE = D.EXPSITE (+)  AND
       A.INCOTERMS = D.INCOTERMS (+) AND
       A.BLOCO = D.BLOCO (+) AND
       A.MESVERSAO = E.MESVERSAO AND
       A.CALDAY = E.CALDAY AND
       A.VERSAO <> 'NAVERSAO' --AND
       --A.CALDAY = E.CALDAY AND
       --A.MESVERSAO = E.MESVERSAO AND
       --A.KEYFIGURE = E.KEYFIGURE
    GROUP BY
       A.MATERIAL,
       A.CALDAY,
       A.MESVERSAO,
       B.GRUPOANALISETXT,
       A.SITE,
       B.SUBSITETXT,
       B.AGRUPTXT,
       B.FAMILIATXT,
       B.SEGTXT,
       A.CUSTOMER,
       C.VENDEDOR,
       C.AGRUP,
       C.CODAGRP,
       C.DESCCLIENTE,
       C.PAISCLIENTE,
       A.PAIS_FAT,
       C.PAISVENDA,
       C.INCOTERM,
       A.EXPSITE,
       A.CURRENCY,
       A.KEYFIGURE
  ) A, MESESGATE B
WHERE
A.CALDAY = B.CALDAY
)

SELECT
    A.MATERIAL,
    A.MESVERSAO,
    A.CALDAY,
    A.GRUPOANALISE,
    A.SITE,
    A.SUBSITE,
    A.AGRUPAMENTO,
    A.FAMILIA,
    B.SEGMENTO_PL SEGMENTO,
    UPPER(A.CUSTOMER) CUSTOMER,
    B.VENDEDOR,
    A.AGRUP,
    A.CODAGRP,
    A.DESCCLIENTE,
    A.PAISCLIENTE,
    A.PAISVENDA,
    A.INCOTERM,
    A.PAIS_FAT,
    A.EXPSITE,
    C.OBSERVACAO,
    SUM(NVL(A.QTD_VENDAS,0)) QTD_VENDAS,
    SUM(NVL(A.VAL_VENDAS,0)) VAL_VENDAS,
    SUM(NVL(A.QTD_CARTEIRA,0)) QTD_CARTEIRA,
    SUM(NVL(A.VAL_CARTEIRA,0)) VAL_CARTEIRA,
    SUM(NVL(A.QTD_BUDGET,0)) QTD_BUDGET,
    SUM(NVL(A.VAL_BUDGET,0)) VAL_BUDGET,
    SUM(NVL(A.QTD_BUDGET_ORIG,0)) QTD_BUDGET_ORIG,
    SUM(NVL(A.VAL_BUDGET_ORIG,0)) VAL_BUDGET_ORIG,
    SUM(NVL(A.QTD_SOP,0)) QTD_SOP,
    SUM(NVL(A.VAL_SOP,0)) VAL_SOP,
    SUM(NVL(A.GATE,0)) QTD_GATE,
    SUM(NVL(A.VAL_GATE,0)) VAL_GATE,
    SUM(NVL(A.GATE_ORIG,0)) QTD_GATE_ORIG,
    SUM(NVL(A.VAL_GATE_ORIG,0)) VAL_GATE_ORIG,
    SUM(NVL(A.LEADTIME,0)) LEADTIME
FROM
    (
      SELECT * FROM VENDAS
      UNION ALL
      SELECT * FROM CARTEIRA
      UNION ALL
      SELECT * FROM BUDGET
      UNION ALL
      SELECT * FROM BUDGET_ORIGINAL
      UNION ALL
      SELECT * FROM SOP
      UNION ALL
      SELECT * FROM GATE
    ) A,

(select CAST(UPPER(a."/B28/S_HWDK7NX") AS VARCHAR(10)) AS CUSTOMER, a."/B28/S_HWP7711" AS VENDEDOR, a."/B28/S_HWPBKK1" AS AGRP, a."/B28/S_HWPO2CZ" AS CODAGRP, b."/BIC/SEGMPL" AS SEGMENTO_PL
from sapr3."/B28/PHWDK7NX"@zwp a, SAPR3."/BI0/MCUSTOMER"@ZWP b where CAST(UPPER(a."/B28/S_HWDK7NX") AS VARCHAR(10))  = b.CUSTOMER) B,
  ( SELECT DISTINCT A.MESREF,
                  A.MATERIAL,
                  B.AGRUPTXT AGRUPAMENTO,
                  A.EXPSITE,
                  A.OBSERVACAO
    FROM TB_ACOMP_VENDAS_MOTIVOS A, V_PRODUTO_PL B
   WHERE A.MATERIAL = B.PRODUTO ) C

WHERE A.CUSTOMER = B.CUSTOMER AND B.SEGMENTO_PL <>(' ') AND B.SEGMENTO_PL IS NOT NULL AND
A.CALDAY = C.MESREF (+) AND A.AGRUPAMENTO = C.AGRUPAMENTO (+) AND A.EXPSITE = C.EXPSITE (+)
GROUP BY
    A.MATERIAL,
    A.MESVERSAO,
    A.CALDAY,
    A.GRUPOANALISE,
    A.SITE,
    A.SUBSITE,
    A.AGRUPAMENTO,
    A.FAMILIA,
    B.SEGMENTO_PL,
    A.CUSTOMER,
    B.VENDEDOR,
    A.AGRUP,
    A.CODAGRP,
    A.DESCCLIENTE,
    A.PAISCLIENTE,
    A.PAISVENDA,
    A.INCOTERM,
    A.PAIS_FAT,
    A.EXPSITE,
    C.OBSERVACAO
;
